import { createTheme } from '@mantine/core';
import {
  TextInputTheme,
  PasswordInputTheme,
  TextareaTheme,
  NumberInputTheme,
  SelectTheme,
  MultiSelectTheme,
  DateInputTheme,
  DateTimePickerTheme,
  DatePickerInputTheme,
  ModalTheme,
  PopoverTheme,
  MenuTheme,
  NotificationTheme,
  AlertTheme,
  BadgeTheme,
  CheckboxTheme,
  CardTheme,
  PaperTheme,
  TabsTheme,
  ActionIconTheme,
  FileInputTheme,
} from './components';

/**
 * VTB-inspired comprehensive theme with glass morphism design
 * Extends all Mantine components with consistent styling
 */
export const theme = createTheme({
  /** VTB-inspired theme configuration */
  primaryColor: 'cyan',
  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
  defaultRadius: 'md',
  white: '#ffffff',
  black: '#0A1F44',
  colors: {
    cyan: [
      '#E6FCFF',
      '#B8F5FF',
      '#8AEDFF',
      '#5CE5FF',
      '#33E3FF',
      '#00D9FF',
      '#00B8D9',
      '#0097B3',
      '#00768C',
      '#005566',
    ],
    blue: [
      '#E6F0FF',
      '#C2DCFF',
      '#9EC8FF',
      '#7AB4FF',
      '#5BA0FF',
      '#3B82F6',
      '#2563B8',
      '#1E4C8F',
      '#163A6B',
      '#0A1F44',
    ],
    dark: [
      '#C1C2C5',
      '#A6A7AB',
      '#909296',
      '#5C5F66',
      '#373A40',
      '#2C2E33',
      '#25262B',
      '#1A1B1E',
      '#141517',
      '#101113',
    ],
  },
  primaryShade: 5,
  shadows: {
    xs: '0 2px 8px rgba(0, 0, 0, 0.1)',
    sm: '0 4px 16px rgba(0, 0, 0, 0.15)',
    md: '0 8px 32px rgba(0, 0, 0, 0.2)',
    lg: '0 12px 48px rgba(0, 217, 255, 0.3)',
    xl: '0 16px 64px rgba(0, 217, 255, 0.4)',
  },
  headings: {
    fontFamily: '"Segoe UI", -apple-system, BlinkMacSystemFont, system-ui, sans-serif',
    fontWeight: '700',
    sizes: {
      h1: { fontSize: '2.5rem', lineHeight: '1.2' },
      h2: { fontSize: '2rem', lineHeight: '1.3' },
      h3: { fontSize: '1.75rem', lineHeight: '1.4' },
      h4: { fontSize: '1.5rem', lineHeight: '1.4' },
      h5: { fontSize: '1.25rem', lineHeight: '1.5' },
      h6: { fontSize: '1rem', lineHeight: '1.5' },
    },
  },
  other: {
    vtbColors: {
      blueDark: '#0A1F44',
      bluePrimary: '#1E4C8F',
      blueMedium: '#2563B8',
      blueLight: '#3B82F6',
      cyan: '#00D9FF',
      cyanLight: '#33E3FF',
    },
  },

  /** Component theme overrides */
  components: {
    TextInput: TextInputTheme,
    PasswordInput: PasswordInputTheme,
    Textarea: TextareaTheme,
    NumberInput: NumberInputTheme,
    Select: SelectTheme,
    MultiSelect: MultiSelectTheme,
    DateInput: DateInputTheme,
    DateTimePicker: DateTimePickerTheme,
    DatePickerInput: DatePickerInputTheme,
    Modal: ModalTheme,
    Popover: PopoverTheme,
    Menu: MenuTheme,
    Notification: NotificationTheme,
    Alert: AlertTheme,
    Badge: BadgeTheme,
    Checkbox: CheckboxTheme,
    Card: CardTheme,
    Paper: PaperTheme,
    Tabs: TabsTheme,
    ActionIcon: ActionIconTheme,
    FileInput: FileInputTheme,
  },
});
